### ISSUE TITLE
Windows - MP2 Ground Zero crash when loading rlava1

### ISSUE THREAD

**Issue by abalfoort** [abalfoort/Q2RTX#7]
As reported by alfredon121: [windows rogue crash](https://steamcommunity.com/app/1089130/discussions/0/1636410430568305533/?ctp=6#c6363065234140269354).

In Debian
```
Thaelite Mines
loading rlava1
Execing maps/default.cfg
Execing maps/rlava1.cfg
]q2rtx: /home/arjen/dev/Q2RTX/src/src/refresh/vkpt/vertex_buffer.c:659: vkpt_light_buffer_upload_to_staging: Assertion `bsp_mesh->num_light_polys + num_model_lights < MAX_LIGHT_POLYS' failed.
Signal: SIGABRT (Aborted)
```

In Windows I see that bsp_mesh->num_light_polys is over 5000:
```
		bsp_mesh->num_light_polys	5332	int
		num_model_lights	0	int
```

**Comment by Alfmaron** [comment]
I tried the new version and the same problem occurs with Ground Zero.
Crash report generated Apr 26 2023, 11:32:29 UTC
by q2rtx 1.7.0-SkacikPL-6f36dbb3, built Apr 23 2023, 10:23:21

Windows version: 6.2 (build 9200) 

Loaded modules:
0x00007ff727ad0000 0x00007ff72a21e000 q2rtx (version 1.7.0.0, symbols none) *
0x00007fffe79b0000 0x00007fffe7ba8000 ntdll (version 6.2.19041.1806, symbols export)
0x00007fffe6fc0000 0x00007fffe707d000 KERNEL32 (version 6.2.19041.1889, symbols export)
0x00007fffe53f0000 0x00007fffe56be000 KERNELBASE (version 6.2.19041.1889, symbols export)
0x00007fffe5b30000 0x00007fffe5b9b000 WS2_32 (version 6.2.19041.546, symbols export)
0x00007fffe7080000 0x00007fffe71a5000 RPCRT4 (version 6.2.19041.1806, symbols export)
0x00007fffe65c0000 0x00007fffe6760000 USER32 (version 6.2.19041.1503, symbols export)
0x00007fffe5320000 0x00007fffe5342000 win32u (version 6.2.19041.1889, symbols export)
0x00007fffe7260000 0x00007fffe728a000 GDI32 (version 6.2.19041.1620, symbols export)
0x00007fffe57c0000 0x00007fffe58cb000 gdi32full (version 6.2.19041.1706, symbols export)
0x00007fffddb30000 0x00007fffddb57000 WINMM (version 6.2.19041.546, symbols export)
0x00007fffe5280000 0x00007fffe531d000 msvcp_win (version 6.2.19041.789, symbols export)
0x00007fffe6460000 0x00007fffe64fe000 msvcrt (version 7.0.19041.546, symbols export)
0x00007fffe56c0000 0x00007fffe57c0000 ucrtbase (version 6.2.19041.789, symbols export)
0x00007fffb4970000 0x00007fffb4ad5000 vulkan-1 (version 1.3.224.0, symbols export)
0x00007fffe76d0000 0x00007fffe7700000 IMM32 (version 6.2.19041.546, symbols export)
0x00007fffe62d0000 0x00007fffe63fa000 ole32 (version 6.2.19041.1202, symbols export)
0x00007fffe7370000 0x00007fffe76c4000 combase (version 6.2.19041.1741, symbols export)
0x00007fffe7780000 0x00007fffe784d000 OLEAUT32 (version 6.2.19041.985, symbols export)
0x00007fffe6010000 0x00007fffe60be000 ADVAPI32 (version 6.2.19041.1682, symbols export)
0x00007fffe5a90000 0x00007fffe5b2c000 sechost (version 6.2.19041.1865, symbols export)
0x00007fffe5230000 0x00007fffe527e000 CFGMGR32 (version 6.2.19041.1620, symbols export)
0x00007fffe5ba0000 0x00007fffe600f000 SETUPAPI (version 6.2.19041.1741, symbols export)
0x00007fffe5350000 0x00007fffe5377000 bcrypt (version 6.2.19041.1023, symbols export)
0x00007fffe67e0000 0x00007fffe6f24000 SHELL32 (version 6.2.19041.1865, symbols export)
0x00007fffdf350000 0x00007fffdf35a000 VERSION (version 6.2.19041.546, symbols export)
0x00007fffe39d0000 0x00007fffe3ac3000 dxgi (version 6.2.19041.1806, symbols export)
0x00007fffe4890000 0x00007fffe48fa000 mswsock (version 6.2.19041.546, symbols export)
0x00007fffe2ad0000 0x00007fffe2b6e000 uxtheme (version 6.2.19041.1620, symbols export)
0x00007fffe6510000 0x00007fffe65bd000 SHCORE (version 6.2.19041.1865, symbols export)
0x00007fffdf640000 0x00007fffdf6ee000 mscms (version 6.2.19041.746, symbols export)
0x00007fffe4fd0000 0x00007fffe4ffe000 USERENV (version 6.2.19041.572, symbols export)
0x00007fffdf620000 0x00007fffdf631000 ColorAdapterClient (version 6.2.19041.546, symbols export)
0x00007fffb5340000 0x00007fffb5383000 icm32 (version 6.2.19041.546, symbols export)
0x00007fffe2ff0000 0x00007fffe3002000 kernel.appcore (version 6.2.19041.546, symbols export)
0x00007fff95b80000 0x00007fff994b2000 nvoglv64 (version 31.0.15.2756, symbols export)
0x00007fffe0e00000 0x00007fffe0e14000 WTSAPI32 (version 6.2.19041.546, symbols export)
0x00007fffe5980000 0x00007fffe5a02000 bcryptprimitives (version 6.2.19041.1415, symbols export)
0x00007fffe4cc0000 0x00007fffe4cd2000 msasn1 (version 6.2.19041.546, symbols export)
0x00007fffdf310000 0x00007fffdf341000 cryptnet (version 6.2.19041.906, symbols export)
0x00007fffe50d0000 0x00007fffe5226000 CRYPT32 (version 6.2.19041.1889, symbols export)
0x00007fffdf030000 0x00007fffdf178000 drvstore (version 6.2.19041.1566, symbols export)
0x00007fffe4e80000 0x00007fffe4eac000 devobj (version 6.2.19041.1620, symbols export)
0x00007fffe4b30000 0x00007fffe4b60000 wldp (version 6.2.19041.1806, symbols export)
0x00007fffe4a80000 0x00007fffe4a8c000 cryptbase (version 6.2.19041.546, symbols export)
0x00007fffe5380000 0x00007fffe53e8000 WINTRUST (version 6.2.19041.1865, symbols export)
0x00007fffe3dd0000 0x00007fffe3e03000 ntmarta (version 6.2.19041.546, symbols export)
0x00007fffe71b0000 0x00007fffe7259000 clbcatq (version 2001.12.10941.16384, symbols export)
0x00007fffe0f60000 0x00007fffe10b4000 WinTypes (version 6.2.19041.1682, symbols export)
0x00007fffe7850000 0x00007fffe7965000 MSCTF (version 6.2.19041.1806, symbols export)
0x00007fffcff00000 0x00007fffd015f000 msxml6 (version 6.30.19041.1023, symbols export)
0x00007fffdd260000 0x00007fffdd359000 textinputframework (version 6.2.19041.1806, symbols export)
0x00007fffe1f40000 0x00007fffe229e000 CoreUIComponents (version 6.2.19041.546, symbols export)
0x00007fffe2620000 0x00007fffe2712000 CoreMessaging (version 6.2.19041.746, symbols export)
0x00007fffe31f0000 0x00007fffe3984000 windows.storage (version 6.2.19041.1865, symbols export)
0x00007fffe5a30000 0x00007fffe5a85000 shlwapi (version 6.2.19041.1706, symbols export)
0x00007fffdde90000 0x00007fffddecb000 dxcore (version 6.2.19041.546, symbols export)
0x00007fff9d3d0000 0x00007fff9d69f000 nvspcap64 (version 3.26.0.160, symbols export)
0x00007fffe5010000 0x00007fffe502f000 profapi (version 6.2.19041.844, symbols none)
0x00007fffe2d00000 0x00007fffe2d2f000 dwmapi (version 6.2.19041.746, symbols export)
0x00007fffe5a10000 0x00007fffe5a2d000 imagehlp (version 6.2.19041.1415, symbols export)
0x00007fffe4a90000 0x00007fffe4aa8000 CRYPTSP (version 6.2.19041.546, symbols export)
0x00007fffe41a0000 0x00007fffe41d4000 rsaenh (version 6.2.19041.1052, symbols export)
0x00007fffe39a0000 0x00007fffe39c3000 gpapi (version 6.2.19041.1865, symbols export)
0x00007fff9a2f0000 0x00007fff9c019000 nvcuda64 (version 31.0.15.2756, symbols export)
0x00007fffd7040000 0x00007fffd77af000 nvapi64 (version 31.0.15.2756, symbols export)
0x00007fff79d60000 0x00007fff8042b000 nvrtum64 (version 31.0.15.2756, symbols export)
0x00007fffca620000 0x00007fffca6ce000 NvCameraAllowlisting64 (version 7.1.816.0, symbols export)
0x00007fff99aa0000 0x00007fff9a2ef000 NvCamera64 (version 7.1.816.0, symbols export)
0x00007fffe0dd0000 0x00007fffe0dd7000 XINPUT9_1_0 (version 6.2.19041.1, symbols export)
0x00007fffe3990000 0x00007fffe399d000 HID (version 6.2.19041.546, symbols export)
0x00007fffdf850000 0x00007fffdfa04000 WindowsCodecs (version 6.2.19041.1706, symbols export)
0x00007fffc2c40000 0x00007fffc2c85000 DINPUT8 (version 6.2.19041.1, symbols export)
0x00007fffe1ae0000 0x00007fffe1d43000 d3d11 (version 6.2.19041.1865, symbols export)
0x00007fffdd100000 0x00007fffdd252000 inputhost (version 6.2.19041.1741, symbols export)
0x00007fffe0ca0000 0x00007fffe0d96000 PROPSYS (version 7.0.19041.1741, symbols export)
0x00007fffb3820000 0x00007fffb3947000 opengl32 (version 6.2.19041.1806, symbols export)
0x00007fffc3780000 0x00007fffc37ac000 GLU32 (version 6.2.19041.1806, symbols export)
0x00007fffdff50000 0x00007fffe0047000 AppXDeploymentClient (version 6.2.19041.1865, symbols export)
0x00007fffe4650000 0x00007fffe469b000 powrprof (version 6.2.19041.546, symbols export)
0x00007fffe4510000 0x00007fffe4522000 UMPDC (version unknown, symbols export)
0x00007fffe3e40000 0x00007fffe3e9a000 WINSTA (version 6.2.19041.546, symbols export)
0x00007fffdedc0000 0x00007fffdee93000 Windows.Gaming.Input (version 6.2.19041.1566, symbols export)
0x00007fffdfab0000 0x00007fffdfcb0000 twinapi.appcore (version 6.2.19041.1865, symbols export)
0x00007fffddca0000 0x00007fffddd25000 MMDevApi (version 6.2.19041.1503, symbols export)
0x00007fffc31d0000 0x00007fffc3352000 AUDIOSES (version 6.2.19041.1865, symbols export)
0x00007fffe2c00000 0x00007fffe2c14000 resourcepolicyclient (version 6.2.19041.546, symbols export)
0x00007fff95770000 0x00007fff95b74000 d3dcompiler_47_64 (version 6.3.9600.16384, symbols export)
0x00007fffddb60000 0x00007fffddc1e000 nvldumdx (version 31.0.15.2756, symbols export)
0x00007fffd39b0000 0x00007fffd703d000 nvwgf2umx (version 31.0.15.2756, symbols export)
0x00007fffe4530000 0x00007fffe456b000 iphlpapi (version 6.2.19041.1865, symbols export)
0x00007fffc8260000 0x00007fffc8997000 MessageBus (version 1.22.2758.1620, symbols export)
0x00007fffe6760000 0x00007fffe6768000 NSI (version 6.2.19041.610, symbols export)
0x00007fffdf540000 0x00007fffdf55d000 dhcpcsvc (version 6.2.19041.546, symbols export)
0x00007fff93f20000 0x00007fff9555c000 gamex86_64 (version unknown, symbols export)
0x00007fffdb9a0000 0x00007fffdba4c000 TextShaping (version unknown, symbols export)
0x00007fffda260000 0x00007fffda444000 dbghelp (version 6.2.19041.867, symbols export)

Exception information:
Code: 0x80000003
Address: 0x00007ff72836e3d5 (q2rtx)

Thread context:
RIP: 0x00007ff72836e3d5 RBP: 0x0000000000000000 RSP: 0x000000598a0fef40
RAX: 0x0000000000000004 RBX: 0x0000000000000000 RCX: 0x48312a8c8c0f0000
RDX: 0x00000229922b0000 RSI: 0x0000000000000000 RDI: 0x000000598a0ff410
R8 : 0x0000022992245940 R9 : 0x0000000000000001 R10: 0x0000000000008000
R11: 0x000000598a0fec90 R12: 0x0000000000000000 R13: 0x0000000000000000
R14: 0x0000000000000000 R15: 0x0000000000000000

Stack trace:
0: 0x00007ff7286cce70 0x00007ff7286ccdf0 0x0000022900000293 0x00007ff727cbed35 q2rtx!0x00007ff72836e3d5
1: 0x00007ff7286cce70 0x00007ff7286ccdf0 0x0000000000000293 0x00007ff727cbed35 q2rtx!0x00007ff72836e193
2: 0x00007ff7286cce70 0x00007ff7286ccdf0 0xcccccccc00000293 0x0000000000000000 q2rtx!0x00007ff72837173f
3: 0x00007ff7286db901 0x00007ff728884b20 0x0000022a9180b2f0 0x0000005900000000 q2rtx!0x00007ff727cbed35
4: 0x00007ff729b740b8 0x000000000000002b 0x0000000000000054 0x00007ff727b42520 q2rtx!0x00007ff727d221e1
5: 0xffffffffffffffff 0x000002299455fb00 0x0000000000000000 0xcccccccc00000001 q2rtx!0x00007ff727b40893
6: 0xcccccccccccccccc 0x0000000044460800 0x0000596a80e309e5 0xcccccccccccccccc q2rtx!0x00007ff727b36d0f
7: 0x0000000000000064 0xcccccccccccccccc 0x00000229ac8e8288 0x0000596a000002a8 q2rtx!0x00007ff727b31c79
8: 0x0000000000000064 0x00007ff727b85464 0xcccccccccccccccc 0x0000000604f1b6db q2rtx!0x00007ff727cd2378
9: 0x00007ff700000004 0x00007ff728b599c0 0x00000229922b3f30 0x00000c0100000000 q2rtx!0x00007ff727b86b54
10: 0x0000022900000004 0x00007ff728b599c0 0x0000000000000000 0x0000000000b20bf0 q2rtx!0x00007ff727c01509
11: 0x00007ff727ad0000 0x0000000000000000 0x00000229922b3f64 0x00007ff700000001 q2rtx!0x00007ff727c00350
12: 0x00007ff727ae5fbe 0x00007ff700000002 0x0000000000000000 0x0000000000000000 q2rtx!0x00007ff728263d42
13: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 q2rtx!0x00007ff728263bee
14: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 q2rtx!0x00007ff728263aae
15: 0x0000005989e6c000 0x0000000000000000 0x0000000000000000 0x0000000000000000 q2rtx!0x00007ff728263dde
16: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 KERNEL32!0x00007fffe6fd7034
17: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 ntdll!0x00007fffe7a02651

**Comment by abalfoort** [comment]
Fixed with commit commit 0eaca60

**Comment by Alfmaron** [comment]
Great, it works. Thanks!
Can You fix the issues with other mods like Citadel, Juggernaut freezing after intro movie? Oblivion and Quake225ACU don't load all elements those can be finished?

**Comment by abalfoort** [comment]
I'm not planning on fixing any other mods for Q2RTX. It is a lot of work to create the source code to create the libraries (.so for Linux and .dll for Windows) that are needed.

**Comment by Alfmaron** [comment]
Ok, thanks for fixing this. 
Cheers!
