### ISSUE TITLE
Zaero's q2rtx_media.pkz and upscaled textures?

### ISSUE THREAD

**Issue by 2mg** [abalfoort/Q2RTX#9]
Hi,

so the q2rtx_media.pkz inside zaero folder contains upscaled textures/models.
I'd like to play in OGL mode with these textures.

However, they aren't immediately applied in-game with OpenGL.
The "use new textures" (gl_use_hd_assets) option is missing - in fact quite a few of video settings are missing when launching RTX Zaero compared to Quake 2 RTX.

What I found out is that launching Q2RTX_170_Win11_20230909 with "+set game zaero" **locks** the q2rtx_media.pkz from BaseQ2 folder, instead of from Zaero folder - _this causes textures to clash/mismatch_.

I know Q2RTX implemented the feature of loading replacement textures, but the process of getting Zaero to work with your fork/build is a bit weird.

I have added another community upscaled texture pack for BaseQ2 content (Q2's base game models) to Zaero by simply extracting to a folder "models" for things that Zaero doesn't have and otherwise pulls from baseq2 .pkz and/or .pak, and it works nicely even with your included upscaled pack in Zaero .pkz - _but only if I rename the baseq2 .pkz_.

I currently have a hacky workaround by renaming the .pkz file in baseq2, and everything is loaded from the Zaero .pkz, but is this supposed to work like this - why not load stuff from Zaero .pkz and then the "missing" content from either Zaero .pak, and then from BaseQ2 .pkz/.pak?

PS: for some reason "ctank" folder has to be outside of "tank" folder to make ctank model with upscaled texture, dunno why.
PSS: is it possible to update Zaero with 1.1 version, since it has a new .dll?

**Comment by abalfoort** [comment]
I think this issue belongs upstream. I see you reported the bug there as well. I don't have the knowledge to fix that. 
I use the Yamagi Quake II project for the MPs. So, any updates there will eventually find its way to this project.
